# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d383a72a88735845b0b93e5eec77e027ef9f7995f64bccbfe647fd4eb06b16e39e847bfc049b72e37e7ddaf616c47c548b468b94cca8bf160da47a104adecf

test:
  secret_key_base: 27ce6e6d64518a6ab0e98f96cbb74151171c35417653fd31b4d442086e4c55671b3ad79a69c13d5074ddc171c46cba0ec82a08361751b32c9f7151864dad8925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
